version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: '7.1.x-webserver'
    restart: 'always'
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - "8181:80"
      - "8282:443"
    links: 
      - mysql
    depends_on:
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./forum}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: '5.6-mysql'
    restart: 'always'
    ports:
      - "8383:3306"
    command: --init-file /var/www/dump/forum.sql
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/www/html
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
      - ./dump/forum.sql:/var/www/dump/forum.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum
      - MYSQL_TABLE_PREFIX=qa_
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test