version: '3'

services:
    www:
        build: docker/www/
        container_name: www
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - mysql
    mysql:
        image: mysql:5.6
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./dump/forum.sql:/docker-entrypoint-initdb.d/forum.sql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=forum
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
