---
- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install php5
  sudo: yes
  apt: pkg=php5 state=latest

- name: Install php5-fpm
  sudo: yes
  apt: pkg=php5-fpm state=latest

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-intl
    - php5-mcrypt
    - php5-curl
    - php5-imagick
    - php5-common
    - php5-memcache
    - php5-mysql
    - php5-readline
    - php5-sqlite
    - php5-gd
  when: php.packages is defined

- include: configure.yml
- include: pecl.yml
- include:  php_ini_configure.yml
